--- Diretorios ~/.local/share/nvim || Plugins site/pack/packer/start
--- instalar python-pynvim arch sudo pacman -S python-pynvim

require "config.options"
require "config.keymaps"
require "config.colorscheme"
require "plugins.plugins"        --- Para ler o packer.vim
require "plugins.complete"
require "plugins.blankline"
require "plugins.hlargs"
require "plugins.lualine"
require "plugins.discord"
require "plugins.limelight"
require "plugins.colors"
require "plugins.cmp"
require "plugins.config"
require "plugins.telescope"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.nvim-tree"
require "plugins.toggleterm"
require "plugins.project"
require "plugins.impatient"
require "plugins.alpha"
require "plugins.whichkey"
require "plugins.autocommands"
require "plugins.twilight"
require "plugins.zenMode"
